- name: Tao User AD vao Phong CNTT
  hosts: winservers
  gather_facts: no
  
  vars:
    user_pass: "Tini@2024@"
    # ĐÂY LÀ DÒNG QUAN TRỌNG NHẤT:
    target_path: "OU=08 PHONG CNTT,OU=TINIGROUP,DC=huylv,DC=xyz"

  tasks:
    - name: Tao User NhanVienMoi
      microsoft.ad.user:
        name: NhanVienMoihihi
        password: "{{ user_pass }}"
        firstname: Nguyen
        surname: Van A
        email: nguyenvana@huylv.xyz
        path: "{{ target_path }}"  # Ansible sẽ nhét vào đúng chỗ này
        enabled: yes
        state: present
        groups:
          - Domain Users