- name: Tao User AD vao Phong CNTT
  hosts: winservers
  gather_facts: no
  
  vars:
    user_pass: "MatKhauManh@123"
    target_path: "OU=08 PHONG CNTT,OU=TINIGROUP,DC=huylv,DC=xyz"

  tasks:
    # 1. TẠO USER
    - name: Tao User NhanVienMoi
      microsoft.ad.user:
        name: NhanVienMoihihi
        password: "{{ user_pass }}"
        firstname: Nguyen
        surname: Van D
        email: nguyenvanahihi@huylv.xyz
        path: "{{ target_path }}"
        enabled: yes
        state: present

    # 2. ADD GROUP (Dùng PowerShell cho chắc ăn)
    - name: Add User vao Group Admin
      win_shell: |
        Add-ADGroupMember -Identity "Administrators" -Members "NhanVienMoihihi" -ErrorAction SilentlyContinue