- name: Tao User AD Full Thong Tin
  hosts: winservers
  gather_facts: no
  
  vars:
    user_pass: "MatKhauManh@123"
    target_path: "OU=08 PHONG CNTT,OU=TINIGROUP,DC=huylv,DC=xyz"
    
    nhanvien:
      ho: "Nguyen Phuc"
      ten: "Thinh"
      username: "it.sys"
      upn_full: "it.sys@huylv.xyz"
      email: "it.sys@tinigroup.vn"
      chucdanh: "IT System Administrator"
      phongban: "P. CNTT"
      congty: "TINIGROUP"

  tasks:
    - name: Tao va Cap nhat thong tin User
      microsoft.ad.user:
        # --- PHẦN NÀY QUYẾT ĐỊNH TÊN HIỂN THỊ ---
        name: "{{ nhanvien.ho }} {{ nhanvien.ten }}"  # Sẽ ra: "Luong Van Huy" (CN)
        
        # --- PHẦN NÀY QUYẾT ĐỊNH TÊN ĐĂNG NHẬP ---
        sam_account_name: "{{ nhanvien.username }}"   # Sẽ ra: "it.hd"
        upn: "{{ nhanvien.upn_full }}"                # Sẽ ra: "it.hd@huylv.xyz"
        
        # --- Các thông tin khác ---
        firstname: "{{ nhanvien.ho }}"
        surname: "{{ nhanvien.ten }}"
        display_name: "{{ nhanvien.ho }} {{ nhanvien.ten }}"
        email: "{{ nhanvien.email }}"
        password: "{{ user_pass }}"
        path: "{{ target_path }}"
        password_never_expires: yes
        enabled: yes
        
        attributes:
          set:
            title: "{{ nhanvien.chucdanh }}"
            department: "{{ nhanvien.phongban }}"
            company: "{{ nhanvien.congty }}"

    # Add Group (Lưu ý: identity phải dùng sam_account_name)
    - name: Add User vao Group Admin
      win_shell: |
        Add-ADGroupMember -Identity "Administrators" -Members "{{ nhanvien.username }}" -ErrorAction SilentlyContinue