- name: Tao User AD Full Thong Tin
  hosts: winservers
  gather_facts: no
  
  vars:
    user_pass: "MatKhauManh@123"
    target_path: "OU=08 PHONG CNTT,OU=TINIGROUP,DC=huylv,DC=xyz"
    
    nhanvien:
      ho: "Luong Van"
      ten: "Huy"
      username: "it.hd"
      email: "it.hd@tinigroup.vn"
      chucdanh: "IT Helpdesk"
      phongban: "P. CNTT"
      congty: "TINIGROUP"

  tasks:
    # 1. TẠO USER
    - name: Tao va Cap nhat thong tin User
      microsoft.ad.user:
        name: "{{ nhanvien.username }}"
        firstname: "{{ nhanvien.ho }}"
        surname: "{{ nhanvien.ten }}"
        display_name: "{{ nhanvien.ho }} {{ nhanvien.ten }}"
        email: "{{ nhanvien.email }}"
        password: "{{ user_pass }}"
        path: "{{ target_path }}"
        password_never_expires: yes
        enabled: yes
        
        # SỬA LẠI ĐOẠN NÀY:
        attributes:
          set:
            title: "{{ nhanvien.chucdanh }}"
            department: "{{ nhanvien.phongban }}"
            company: "{{ nhanvien.congty }}"

    # 2. ADD GROUP ADMIN
    - name: Add User vao Group Admin
      win_shell: |
        Add-ADGroupMember -Identity "Administrators" -Members "{{ nhanvien.username }}" -ErrorAction SilentlyContinue