- name: Quan ly User AD (Doc tu File)
  hosts: winservers
  gather_facts: no
  
  vars:
    # Bản đồ phòng ban (Giữ nguyên không đổi)
    ou_map:
      P.CNTT: "OU=08 PHONG CNTT,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.NHAN SU: "OU=07 PHONG NHAN SU,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.PHAP CHE: "OU=06 PHONG PHAP CHE,OU=TINIGROUP,DC=tinigroup,DC=local"
      GOLF RIVERPARK: "OU=GOLF RIVERPARK,OU=TINIGROUP,DC=tinigroup,DC=local"

      P.KINH DOANH: "OU=PHONG KINH DOANH,OU=05 KHOI KINH DOANH,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.MARKETING: "OU=PHONG MARKETING,OU=05 KHOI KINH DOANH,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.THIET KE: "OU=PHONG THIET KE,OU=05 KHOI KINH DOANH,OU=TINIGROUP,DC=tinigroup,DC=local"

      P.KE TOAN: "OU=KE TOAN,OU=04 KHOI TAI CHINH KE TOAN - DAU TU,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.TAI CHINH: "OU=TAI CHINH - DAU TU,OU=04 KHOI TAI CHINH KE TOAN - DAU TU,OU=TINIGROUP,DC=tinigroup,DC=local"

      P.HCQT: "OU=02 PHONG HCQT,OU=03 KHOI VAN HANH,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.QL VAN HANH: "OU=03 PHONG QLVH,OU=03 KHOI VAN HANH,OU=TINIGROUP,DC=tinigroup,DC=local"

      P.PHAP LY DU AN: "OU=01 PHAP LY DU AN,OU=02 KHOI PHAT TRIEN DU AN,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.QL DU AN: "OU=02 QUAN LY DU AN,OU=02 KHOI PHAT TRIEN DU AN,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.R AND D: "OU=03 NGHIEN CUU & PHAT TRIEN,OU=02 KHOI PHAT TRIEN DU AN,OU=TINIGROUP,DC=tinigroup,DC=local"
      
      P.QL KY THUAT: "OU=01 PHONG QUAN LY KY THUAT,OU=09 KHOI QUAN LY DU AN,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.DIEU PHOI DA: "OU=02 PHONG DIEU PHOI DU AN,OU=09 KHOI QUAN LY DU AN,OU=TINIGROUP,DC=tinigroup,DC=local"
      P.BAN QLDA: "OU=03 CAC BAN QUAN LY DU AN,OU=09 KHOI QUAN LY DU AN,OU=TINIGROUP,DC=tinigroup,DC=local"

  tasks:
    - name: Tao hoac Cap nhat User
      microsoft.ad.user:
        identity: "{{ item.split(',')[0] | trim }}"
        sam_account_name: "{{ item.split(',')[0] | trim }}"
        upn: "{{ item.split(',')[0] | trim }}@tinigroup.vn"
        
        name: "{{ item.split(',')[1] | trim }}" 
        display_name: "{{ item.split(',')[1] | trim }}"
        firstname: "{{ (item.split(',')[1] | trim).split(' ')[0] }}"
        surname: "{{ (item.split(',')[1] | trim).split(' ')[1:] | join(' ') }}"
        
        email: "{{ item.split(',')[3] | trim }}"
        password: "Tini@2024@" # Lấy mật khẩu từ vars.yml truyền vào
        path: "{{ ou_map[chon_phong] }}"
        
        enabled: yes
        password_never_expires: yes
        state: present
        
        attributes:
          set:
            title: "{{ item.split(',')[2] | trim }}"
            company: "TINIGROUP"
            department: "{{ chon_phong }}"
      
      # ĐỌC FILE USER_LIST.TXT
      loop: "{{ lookup('file', 'user_list.txt').splitlines() | select('match', '^.+$') | list }}"
      loop_control:
        label: "Xu ly: {{ item.split(',')[0] }}"

    # --- TASK 2: THÊM VÀO NHÓM (Dùng Try/Catch để không bao giờ lỗi) ---
    - name: Add User vao Group an toan
      win_shell: |
        $user = "{{ item.split(',')[0] | trim }}"
        $group = "Domain Users"
        
        # Thử thêm vào nhóm
        try {
            Add-ADGroupMember -Identity $group -Members $user -ErrorAction Stop
            Write-Host "Da them $user vao $group"
        }
        catch {
            # Nếu lỗi (do đã tồn tại), chỉ in ra thông báo và không làm chết Pipeline
            Write-Host "User $user da ton tai trong nhom $group. Bo qua."
        }
      loop: "{{ lookup('file', 'user_list.txt').splitlines() | select('match', '^.+$') | list }}"
      loop_control:
        label: "Add Group: {{ item.split(',')[0] }}"

    - name: Force Sync Azure AD
      win_shell: |
        if (Get-Module -ListAvailable -Name ADSync) { Start-ADSyncSyncCycle -PolicyType Delta }
      ignore_errors: yes