- name: Quan ly User Windows
  hosts: winservers
  gather_facts: no
  
  vars:
    user_pass: "MatKhauManh@123"

  tasks:
    - name: Tao User Windows Moi
      ansible.windows.win_user:
        name: NhanVienMoi1
        password: "{{ user_pass }}"
        fullname: Nguyen Van B
        groups:
          - Administrators  # Chỉ cần liệt kê nhóm muốn thêm
        groups_action: add  # <--- DÒNG QUAN TRỌNG NHẤT: Chỉ thêm, không xóa nhóm cũ
        state: present