- name: Tao User AD Full Thong Tin
  hosts: winservers
  gather_facts: no
  
  vars:
    # Thông tin cấu hình chung
    user_pass: "MatKhauManh@123"  # <--- Sửa lại mật khẩu
    target_path: "OU=08 PHONG CNTT,OU=TINIGROUP,DC=huylv,DC=xyz"
    
    # Thông tin nhân viên (Sau này có thể nhập từ Jenkins Parameter)
    nhanvien:
      ho: "Luong Van"
      ten: "Huy"
      username: "it.hd"  # User logon name
      email: "it.hd@tinigroup.vn"
      chucdanh: "IT Helpdesk"
      phongban: "P. CNTT"
      congty: "TINIGROUP" # Ví dụ tên công ty

  tasks:
    - name: Tao va Cap nhat thong tin User
      microsoft.ad.user:
        # --- Thông tin cơ bản (Giữ nguyên) ---
        name: "{{ nhanvien.username }}"
        firstname: "{{ nhanvien.ho }}"
        surname: "{{ nhanvien.ten }}"
        display_name: "{{ nhanvien.ho }} {{ nhanvien.ten }}"
        email: "{{ nhanvien.email }}"
        password: "{{ user_pass }}"
        path: "{{ target_path }}"
        password_never_expires: yes
        enabled: yes
        
        # --- THÔNG TIN TỔ CHỨC (Sửa lại phần này) ---
        # Nhét hết Chức danh, Phòng ban vào trong 'attributes'
        attributes:
          title: "{{ nhanvien.chucdanh }}"      # Job Title đổi thành title
          department: "{{ nhanvien.phongban }}" # Department
          company: "{{ nhanvien.congty }}"      # Company
        
        # Đường dẫn OU
        path: "{{ target_path }}"
        state: present

    # 2. ADD GROUP ADMIN (Dùng PowerShell cho chắc ăn)
    - name: Add User vao Group Admin
      win_shell: |
        Add-ADGroupMember -Identity "Administrators" -Members "{{ nhanvien.username }}" -ErrorAction SilentlyContinue