- name: Tao User AD Full Thong Tin
  hosts: winservers
  gather_facts: no
  
  vars:
    user_pass: "Tini@2024@"
    
    ou_map:
      # Khối 1
      CNTT: "OU=08 PHONG CNTT,OU=TINIGROUP,DC=huylv,DC=xyz"
      NHAN_SU: "OU=07 PHONG NHAN SU,OU=TINIGROUP,DC=huylv,DC=xyz"
      PHAP_CHE: "OU=06 PHONG PHAP CHE,OU=TINIGROUP,DC=huylv,DC=xyz"
      GOLF_RIVERPARK: "OU=GOLF RIVERPARK,OU=TINIGROUP,DC=huylv,DC=xyz"

      # Khối Kinh Doanh
      KINH_DOANH: "OU=PHONG KINH DOANH,OU=05 KHOI KINH DOANH,OU=TINIGROUP,DC=huylv,DC=xyz"
      MARKETING: "OU=PHONG MARKETING,OU=05 KHOI KINH DOANH,OU=TINIGROUP,DC=huylv,DC=xyz"
      THIET_KE: "OU=PHONG THIET KE,OU=05 KHOI KINH DOANH,OU=TINIGROUP,DC=huylv,DC=xyz"

      # Khối Tài Chính
      KE_TOAN: "OU=KE TOAN,OU=04 KHOI TAI CHINH KE TOAN - DAU TU,OU=TINIGROUP,DC=huylv,DC=xyz"
      TAI_CHINH: "OU=TAI CHINH - DAU TU,OU=04 KHOI TAI CHINH KE TOAN - DAU TU,OU=TINIGROUP,DC=huylv,DC=xyz"

      # Khối Vận Hành
      HCQT: "OU=02 PHONG HCQT,OU=03 KHOI VAN HANH,OU=TINIGROUP,DC=huylv,DC=xyz"
      QL_VAN_HANH: "OU=03 PHONG QLVH,OU=03 KHOI VAN HANH,OU=TINIGROUP,DC=huylv,DC=xyz"

      # Khối Dự Án
      PHAP_LY_DU_AN: "OU=01 PHAP LY DU AN,OU=02 KHOI PHAT TRIEN DU AN,OU=TINIGROUP,DC=huylv,DC=xyz"
      QL_DU_AN: "OU=02 QUAN LY DU AN,OU=02 KHOI PHAT TRIEN DU AN,OU=TINIGROUP,DC=huylv,DC=xyz"
      R_AND_D: "OU=03 NGHIEN CUU & PHAT TRIEN,OU=02 KHOI PHAT TRIEN DU AN,OU=TINIGROUP,DC=huylv,DC=xyz"
    
    nhanvien:
      ho: "Luong Van"
      ten: "BBB"
      username: "kt.ba"  # Sẽ ra: "it.hd"
      upn_full: "kt.ba@huylv.xyz"
      email: "kt.ba@tinigroup.vn"
      chucdanh: "Ke Toan"
      phongban: "P. KE TOAN"
      congty: "TINIGROUP"

  tasks:
    - name: Tao va Cap nhat thong tin User
      microsoft.ad.user:
        # --- DÒNG QUYẾT ĐỊNH: Tìm user dựa trên ID đăng nhập ---
        identity: "{{ nhanvien.username }}"      
        # --- PHẦN NÀY QUYẾT ĐỊNH TÊN HIỂN THỊ ---
        name: "{{ nhanvien.ho }} {{ nhanvien.ten }}"  # Sẽ ra: "Luong Van Huy" (CN)
        
        # --- PHẦN NÀY QUYẾT ĐỊNH TÊN ĐĂNG NHẬP ---
        sam_account_name: "{{ nhanvien.username }}"   # Sẽ ra: "it.hd"
        upn: "{{ nhanvien.upn_full }}"                # Sẽ ra: "it.hd@huylv.xyz"
        
        # --- Các thông tin khác ---
        firstname: "{{ nhanvien.ho }}"
        surname: "{{ nhanvien.ten }}"
        display_name: "{{ nhanvien.ho }} {{ nhanvien.ten }}"
        email: "{{ nhanvien.email }}"
        password: "{{ user_pass }}"
        path: "{{ target_path }}"
        password_never_expires: yes
        enabled: yes

        path: "{{ ou_map[chon_phong] }}"
        state: present
        
        attributes:
          set:
            title: "{{ nhanvien.chucdanh }}"
            department: "{{ nhanvien.phongban }}"
            company: "{{ nhanvien.congty }}"

    # Add Group (Lưu ý: identity phải dùng sam_account_name)
    - name: Add User vao Group Admin
      win_shell: |
        Add-ADGroupMember -Identity "Administrators" -Members "{{ nhanvien.username }}" -ErrorAction SilentlyContinue

    - name: Force Sync to Microsoft Azure AD
      win_shell: |
        # Kiểm tra xem có module ADSync không rồi mới chạy
        if (Get-Module -ListAvailable -Name ADSync) {
            Write-Host "Dang dong bo len Cloud..."
            Import-Module ADSync
            Start-ADSyncSyncCycle -PolicyType Delta
        } else {
            Write-Warning "Server nay chua cai Azure AD Connect!"
        }
      ignore_errors: yes # Để lỡ server chưa cài AD Connect thì cũng không bị báo lỗi đỏ    