- name: Quan ly User Windows
  hosts: winservers
  gather_facts: no
  
  vars:
    user_pass: "MatKhauManh@123"

  tasks:
    - name: Tao User Windows Moi
      ansible.windows.win_user:  # <--- DÙNG CÁI NÀY CHUẨN HƠN
        name: NhanVienMoi
        password: "{{ user_pass }}"
        fullname: Nguyen Van A
        groups:
          - Users
          - Administrators # Add vào nhóm Admin luôn cho máu
        state: present