- name: Tao User AD vao Phong CNTT
  hosts: winservers
  gather_facts: no
  
  vars:
    user_pass: "MatKhauManh@123"
    target_path: "OU=08 PHONG CNTT,OU=TINIGROUP,DC=huylv,DC=xyz"

  tasks:
    # 1. TẠO USER (Bỏ phần groups đi)
    - name: Tao User NhanVienMoi
      microsoft.ad.user:
        name: NhanVienMoi
        password: "{{ user_pass }}"
        firstname: Nguyen
        surname: Van A
        email: nguyenvana@huylv.xyz
        path: "{{ target_path }}"
        enabled: yes
        state: present

    # 2. THÊM VÀO GROUP (Dùng task riêng này sẽ không bị lỗi)
    - name: Them NhanVienMoi vao Domain Users
      microsoft.ad.group:
        name: "Domain Users"
        add_members:
          - NhanVienMoi
        state: present