- name: Tu dong Update he thong
  hosts: all
  become: yes  # Chạy với quyền Root
  
  tasks:
    # 1. Nếu là CentOS -> Chạy YUM
    - name: Update toan bo cho CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    # 2. Nếu là Ubuntu -> Chạy APT
    - name: Update toan bo cho Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"