- name: Tu dong Update he thong
  hosts: all # Chạy với quyền Root
  
  tasks:
    # 1. Nếu là CentOS -> Chạy YUM
    - name: Update toan bo cho CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
      become: yes

    # 2. Nếu là Ubuntu -> Chạy APT
    - name: Update toan bo cho Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      become: yes

    - name: Tao thu muc Test trong Root
      file:
        path: /root/Ansible_Da_O_Day  # Tên thư mục bạn muốn tạo
        state: directory
        mode: '0755'
        become: yes

    - name: Tao thu muc Test tren Windows
      win_file:
        path: C:\Ansible_Da_O_Day
        state: directory
      when: ansible_os_family == "Windows"