# --- PHẦN 1: DÀNH RIÊNG CHO LINUX ---
- name: Cau hinh cho nhom Linux
  hosts: webservers  # Chỉ chạy trên nhóm webservers (đã khai báo trong Jenkins)
  become: yes        # Bật sudo cho toàn bộ phần này
  gather_facts: yes  # Lấy thông tin OS
  
  tasks:
    - name: Update CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Tao thu muc Test (Linux)
      file:
        path: /root/Ansible_Da_O_Day
        state: directory
        mode: '0755'

# --- PHẦN 2: DÀNH RIÊNG CHO WINDOWS ---
- name: Cau hinh cho nhom Windows
  hosts: winservers  # Chỉ chạy trên nhóm winservers (đã khai báo trong Jenkins)
  become: no         # TẮT HOÀN TOÀN SUDO (Quan trọng)
  gather_facts: no   # Tắt lấy thông tin kiểu Linux để tránh lỗi Python
  
  tasks:
    - name: Tao thu muc Test (Windows)
      win_file:
        path: C:\Ansible_Da_O_Day
        state: directory